[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_OPTS="--algo=v2 --scheme=history --tiebreak=chunk,begin,length,index"
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
bind -x '"\C-p": vim $(fzf);'

export PATH="$HOME/.local/bin:$PATH"
export EDITOR=nvim

. "$HOME/.atuin/bin/env"
[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
eval "$(atuin init bash)"

# Workaround for Ghostty cursor bug - re-exec bash once on startup
[[ -z "$GHOSTTY_CURSOR_WORKAROUND" ]] && export GHOSTTY_CURSOR_WORKAROUND=1 && exec bash
